# Introduction to NumPy



## Learning Objectives

At the end of the experiment, you will be able to :

* understand the basics of NumPy including its functional objects
* describe the key characteristics of numpy arrays
* understand the difference between Python list and NumPy arrays
* use indexing to slice/select data from NumPy arrays



## Information

#### NumPy

* NumPy stands for 'Numerical Python'
* It is a package for data analysis and scientific computing with Python
* At the heart of NumPy is a basic data type, called the NumPy array. A NumPy array may have a number of dimensions, thus allowing it to represent quantities such as vectors (1D), matrices (2D), or higher dimensional arrays such as tensors.
* It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.

**To know more about Numpy click [here](https://numpy.org/doc/stable/user/whatisnumpy.html)**


#### Difference Between Python list and NumPy array

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

**To know more about the differece between Python list and NumPy arrays click [here](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.)**

#### Import the numpy package under the name np

In [4]:
# Your code here
import numpy as np

####  Create a one-dimensional array

In [5]:
# Your code here
A  = np.arange(10)
a  = [1, 2, 3]
np.array(a)
A.shape

(10,)

#### Create a two-dimensional array

In [6]:
# Your code here
np.array([[1, 2], [3, 4]])
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### Create an array of 10 fives

In [7]:
# Your code here
np.ones(10) * 5
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of 30 zeros


In [8]:
# Your code here
np.zeros(30).shape

(30,)

#### Create a 5 * 5 identity matrix

In [9]:
# Your code here
np.identity(5)
np.eye(5, )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Create a numpy array from a List

In [10]:
# Your code here
l = [1, 2, 3]
np.array(l)
np.array(list(range(20)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

####  Create a 4 * 4 * 4 array with random values

In [31]:
# Your code here
np.random.random((4,4,4))

array([[[1.67081685e-01, 9.62108792e-01, 2.27770230e-01, 8.38335750e-01],
        [6.06225987e-01, 8.24406491e-01, 6.17711569e-01, 1.87241767e-02],
        [4.69482004e-01, 9.10117758e-01, 5.62346684e-01, 4.64768227e-01],
        [9.73307958e-02, 8.71592460e-01, 6.51668347e-01, 9.42675516e-01]],

       [[8.37425315e-01, 2.13963331e-01, 9.97226864e-01, 1.41204441e-01],
        [8.35867521e-01, 5.02083583e-01, 3.32429463e-01, 1.21591623e-01],
        [2.49958053e-01, 5.00175268e-02, 1.48224047e-01, 3.57614944e-01],
        [2.68269104e-01, 3.04509151e-01, 2.32441926e-01, 1.53391513e-02]],

       [[1.39874080e-01, 8.13623846e-01, 7.46230431e-01, 1.89297087e-02],
        [5.60083542e-01, 2.01719197e-01, 4.16546962e-01, 8.70894635e-01],
        [4.66395506e-01, 4.21993333e-01, 4.82087286e-01, 7.31458271e-04],
        [9.60123448e-01, 5.46180775e-01, 2.55208129e-01, 5.47357688e-01]],

       [[2.89408738e-01, 4.94577901e-01, 7.97921539e-01, 5.89514212e-01],
        [4.61955248e-01, 2.30381

#### Create a 10 * 10 array with random values and find the minimum and maximum values 

In [12]:
# Your code here

b = np.random.rand(10,10)
b.max(), np.max(b), b.min()


(0.978159874550106, 0.978159874550106, 0.011032378410976929)

#### Given two arrays *A* and *B*, perform the below operations:

* A + B
* A - B
* A * B
* A / B
* A ** 3

A = np.arange(1,6)

B = np.arange(6, 15, 2)

In [13]:
# Your code here
A = np.arange(1,6)
B = np.arange(6, 15, 2)
print(A, B)

A + B

[1 2 3 4 5] [ 6  8 10 12 14]


array([ 7, 10, 13, 16, 19])

In [14]:
A - B

array([-5, -6, -7, -8, -9])

In [15]:
A * B

array([ 6, 16, 30, 48, 70])

In [16]:
A/B

array([0.16666667, 0.25      , 0.3       , 0.33333333, 0.35714286])

In [17]:
A ** 3

array([  1,   8,  27,  64, 125])

#### Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [18]:
# Your code here
X = np.array([1, 45, 60, 90])
print(np.sin(X[0]))
print(np.cos(X))
print(np.tan(X))

X[0]

0.8414709848078965
[ 0.54030231  0.52532199 -0.95241298 -0.44807362]
[ 1.55740772  1.61977519  0.32004039 -1.99520041]


1

#### Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [19]:
# Your code here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
np.round(X), np.ceil(X), np.floor(X)
# np.round?

(array([  4.,   2.,  44.,  26.,  -1., -10.,  -7.]),
 array([ 5.,  3., 45., 26., -1., -9., -6.]),
 array([  4.,   2.,  44.,  25.,  -2., -10.,  -7.]))

#### Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [20]:
# Your code here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

np.divide(X, Y)

array([0.25, 0.4 , 0.5 ])

#### Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [23]:
# Your code here

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

X ** Y

np.power(X , Y)

array([  1,  32, 729])

#### Use the functions len(), numpy.shape() on array *X*. How do they relate to each other? And to the ndim attribute of the arrays?

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [24]:
# Your code here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
len(X), X.ndim, X.shape

(8, 1, (8,))

#### Use the array X created above and write the commands for the following: 

* Find the sum of all elements
* Find the sum of all elements row wise
* Find the sum of all elements column wise
* Find the max of all elements
* Find the min of all elements in each row
* Find the mean of all elements in each row
* Find the standard deviation column wise

### [8, 6]
### [4, 2]

In [30]:
# Your code here
X1 = np.array([[8,6], [4,2]])

print("sum is",np.sum(X1))
print("\nsum of all elements row wise\n",np.sum(X1, axis=0))
print("\nsum of all elements col wise\n",np.sum(X1, axis=1))
print("\nmax and min",X1.max(), X1.min())
print("\n min row wise",np.min(X1, axis=0))
print("\n mean row wise",np.mean(X1, axis=0))
print("\n standard deviation column wise",np.std(X1, axis=1))

sum is 20

sum of all elements row wise
 [12  8]

sum of all elements col wise
 [14  6]

max and min 8 2

 min row wise [4 2]

 mean row wise [6. 4.]

 standard deviation column wise [1. 1.]
